### ISSUE TITLE
Monitor action’s proxy messing up SSL certificate authority validation for other actions?

### ISSUE THREAD

**Issue by remi** [GitHubSecurityLab/actions-permissions#4]
When using the `GitHubSecurityLab/actions-permissions/monitor@v1` action in a simple Elixir workflow:

```yaml
- uses: GitHubSecurityLab/actions-permissions/monitor@v1
- uses: actions/checkout@v3
- uses: erlef/setup-beam@v1
  with:
    version-file: .tool-versions # (which contains erlang 25.2.1 + elixir 1.14.3-otp-25)
    version-type: strict
- run: mix deps.get
```

The `mix deps.get` action (which fetches package information from https://repo.hex.pm) fails with this error:

```
Notice: 13:26:50.055 [notice] TLS :client: In state :certify at ssl_handshake.erl:2111 generated CLIENT ALERT: Fatal - Unknown CA
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:tls_alert, {:unknown_ca, 'TLS client: In state certify at ssl_handshake.erl:2111 generated CLIENT ALERT: Fatal - Unknown CA\n'}}}]}
```

* [example run that fails](https://github.com/mirego/elixir-boilerplate/actions/runs/5401287308/jobs/9811739649#step:9:55) (with the action)
* [example run that succeeds](https://github.com/mirego/elixir-boilerplate/actions/runs/5401882189/jobs/9812338803#step:8:19) (without the action)

When removing the `GitHubSecurityLab/actions-permissions/monitor@v1` action, `mix deps.get` works as expected.

My guess is that it’s related to the way `mitmproxy` intercepts HTTPS requests.

Is there any more information I can provide to help you guys fix this?

Thank you! ✌️
